/*
 * GlobalEventGroup.h
 *
 *  Created on: Oct 8, 2020
 *      Author: Javier
 */

#ifndef LIBS_AGV_MODULES_INC_GLOBALEVENTGROUP_H_
#define LIBS_AGV_MODULES_INC_GLOBALEVENTGROUP_H_

#ifdef __cplusplus
extern "C" {
#endif


typedef enum{ GEG_EMERGENCY_STOP=1<<0, GEG_PRIORITY_STOP=1<<1,GEG_CONTINUE=1<<2, GEG_COMS_ERROR=1<<3,
	GEG_COMS_RX=1<<4, GEG_CTMOVE_FINISH=1<<5,GEG_CTMOVE_ERROR=1<<6,GEG_MISSION_BLOCK_STARTED =1<<7,GEG_MISSION_PAUSE_CMD=1<<8,
	GEG_MISSION_ABORT_CMD=1<<9, GEG_LOW_POWER=1<<10,GEG_OBJECT_IN_ZONE_2=1<<11,GEG_MISSION_STEP_REACHED=1<<12,
	GEG_CM_ERROR=1<<13, GEG_SS_ERROR=1<<14, GEG_HMI = 1<<15,GEG_EMERGENCY_BUTTON_FREED = 1<<15

}GEG_T;

#define SS_EVENT_MASK (GEG_EMERGENCY_STOP | GEG_PRIORITY_STOP )
#define CC_EVENT_MASK (GEG_HMI | GEG_EMERGENCY_STOP | GEG_PRIORITY_STOP | GEG_CONTINUE | GEG_COMS_ERROR | GEG_COMS_RX | GEG_CTMOVE_FINISH | GEG_CTMOVE_ERROR | GEG_OBJECT_IN_ZONE_2 | GEG_MISSION_STEP_REACHED | GEG_CM_ERROR | GEG_SS_ERROR)
#define ERROR_EVENT_MASK (GEG_COMS_ERROR | GEG_SS_ERROR | GEG_CM_ERROR | GEG_CTMOVE_ERROR)
#define PC_EVENT_MASK (GEG_EMERGENCY_STOP | GEG_PRIORITY_STOP | GEG_CONTINUE | GEG_CTMOVE_FINISH | GEG_CTMOVE_ERROR | GEG_MISSION_BLOCK_STARTED | GEG_MISSION_PAUSE_CMD | GEG_MISSION_ABORT_CMD | GEG_OBJECT_IN_ZONE_2 | GEG_MISSION_STEP_REACHED)

#ifdef __cplusplus
}
#endif


#endif /* LIBS_AGV_MODULES_INC_GLOBALEVENTGROUP_H_ */
