/*
 * HMI.h
 *
 *  Created on: 20 ago. 2020
 *      Author: mdevo
 */

#ifndef HMI_H_
#define HMI_H_

typedef enum{	
	INPUT_BUT_GREEN,
	INPUT_BUT_BLUE,
	INPUT_SW_1,
	INPUT_SW_2,
	INPUT_TOTAL_COUNT
}HMI_INPUT_ID; // MAX LENGTH IS DEFINED BY IO STRUCT IN HMI.C

typedef enum{	
	OUTPUT_BUT_GREEN,
	OUTPUT_BUT_BLUE,
	OUTPUT_LEDSTRIP_RIGHT,
	OUTPUT_LEDSTRIP_LEFT,
	OUTPUT_LEDSTRIP_STOP,
	OUTPUT_BUZZER,
	OUTPUT_TOTAL_COUNT
}HMI_OUTPUT_ID; // MAX LENGTH IS DEFINED BY IO STRUCT IN HMI.C

typedef enum{
	COUNTER,
	LONG_PRESS
} HMI_INPUT_PATTERN;


void HMI_Init();
void HMI?SetInput(OUTPUT_BUT_BLUE, )


#endif /* HMI_H_ */
